[project]
name = "pg-lake-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awscli>=1.36",
    "localstack-client>=2.0",
    "pandas>=3.0.0",
    "pyarrow>=18.0",
]
